// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// 显式加载 .env 文件
// 首先尝试从当前工作目录查找 .env 文件
config({ path: resolve(process.cwd(), ".env") });

// 优先使用 env() 函数，如果为空则使用 process.env 作为备用
const databaseUrl = env("DATABASE_URL") || process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL 环境变量未设置，请在 .env 文件中配置");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});

